### ISSUE TITLE
index.php, site.php Dosyalarını Düzenleme

### ISSUE THREAD

**Issue by DursunCanPoyraz** [volkankalay/laravel-shared-htaccess#1]
Flarum'u paylaşımlı hosting de kullanabilmek için, index.php ve site.php dosyalarını düzenliyorum. Public klasörü içindeki dosyaları bir alt klasöre taşıyorum. server.php dosyasını görmüştüm. Bu dosyayı kullanmak ile benim yaptığım metod arasında bir fark var mıdır? Güvenlik ile ilgili bir sorun teşkil eder mi? 
Dokümantasyon: https://docs.flarum.org/install.html#customizing-paths

**Comment by volkankalay** [comment]
Güvenlik olarak htaccess yönlendirmesi ile belirttiğiniz yöntem arasında fark yaratacağını düşünmüyorum fakat güvenlik konusunda uzman birinden fikir almakta da fayda var.

**Comment by DursunCanPoyraz** [comment]
https://flarumtr.com/d/2189-flarum-dizinleri-ozellestirme burada paylaştım. Oradaki yöntemde güvenlik açığı kalmıyor. .htaccess'de 
```
RewriteRule /\.git / [F,L]
RewriteRule ^auth\.json$ / [F,L]
RewriteRule ^composer\.(lock|json)$ / [F,L]
RewriteRule ^config.php$ / [F,L]
RewriteRule ^flarum$ / [F,L]
RewriteRule ^storage/(.*)?$ / [F,L]
RewriteRule ^vendor/(.*)?$ / [F,L]
```
kuralları girildikten sonra, ilgili dosyalara erişim zaten kapanıyor.
